import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import {Header} from "@/components/organism/Header";
import {Footer} from "@/components/organism/footer";

const PretendardJP = localFont({
  src: '../public/font/PretendardJPVariable.woff2',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={'light'}>
      <body className={`${PretendardJP.className} ${PretendardJP.className}`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
